use_frameworks!

platform :ios, '8.0'

target 'PYBaseImageHandler_Example' do
  pod 'PYBaseImageHandler', :path => '../'

  target 'PYBaseImageHandler_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
